BEGIN TRANSACTION;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100),
  age SMALLINT DEFAULT 20,
  email TEXT UNIQUE NOT NULL,
  entries INT DEFAULT 0,
  joined TIMESTAMP NOT NULL
);
COMMIT;