BEGIN TRANSACTION;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100),
  email TEXT UNIQUE NOT NULL,
  "profileImage" TEXT,
  age SMALLINT DEFAULT 20,
  entries INT DEFAULT 0,
  joined TIMESTAMP NOT NULL
);
COMMIT;